### ISSUE TITLE
Build fails with VS2015

### ISSUE THREAD

**Issue by RogueSheep-nl** [GameTechDev/UE4RealSensePlugin#3]
It seems the solution does not build after upgrading to VS 2015 (Community) mostly of undefined identifiers or types in RealSenseImpl.h, f.e.:
- identifier "PXCFaceConfiguration" is undefined
- identifier "PXCFaceData" is undefined
- use of undefined type 'PXCFaceModule' 
  Seems a library is missing? I'm quite new to C++ and VS, so maybe I'm overseeing something here? 

I had no issues with the previous install of VS, the UE project which I build using this version still runs (in 4.11) without problems, 4.13 wants to rebuild the dll's. Setting up the project from scratch with 4.11 also results in build errors.

**Comment by Lacaion22** [comment]
Hi, I had the exact same problem and found nothing. So I decided to search the undefined class directly and found this one https://github.com/libgdx/gdx-realsense/tree/master/native/include.

Just copy the three .h missing (pxcfaceconfiguration.h, pxcfacemodule.h and pxc3dseg.h) and you can build on VS 2015 :)

Hope this help

**Comment by RogueSheep-nl** [comment]
Thanks for that! 
It does solved the issue. Sadly enough it takes me only to the next issue: now VS complains it cannot find jni.h although the jdk/include dir is in the include path of the project.
 :-/

**Comment by geminim666** [comment]
THE intel updates its SDK now.
And it cant be built now.
Why always changes the CLASS name .:)

**Comment by saseeri** [comment]
Hello, 

I have the same problem that happened to RogueSheep-nl. Did you solve the problem that you have with realsense plugin and UE 4.13? If YES, I really wants to know how can I solve the problem?

Thanks

**Comment by RogueSheep-nl** [comment]
Hi @saseeri, after the last struggle I've put the project on hold as it was taking to much time. You might try the solution @geminim666 suggests.
