### ISSUE TITLE
Any pulse?

### ISSUE THREAD

**Issue by fubar-1** [GameTechDev/UE4RealSensePlugin#4]
This project has had no pulse since May.

Does Intel or anyone intend to maintain / improve it ?

**Comment by fubar-1** [comment]
hello?  anyone home?

**Comment by Alexei-Kondratiev** [comment]
Hello Dave,
You can download my branch with Third Person demo level with Head Tracking control. Have fun!
Best, Alexei

**Comment by fubar-1** [comment]
HI Alexei,
I wandered off in other directions but hope to circle back in a few weeks and will take a look then.
Thanks for updating the project.  It sounds like it's up to the community now.
Best regards, Dave
