### ISSUE TITLE
Plugin not building with ue4.15

### ISSUE THREAD

**Issue by siddardha90** [GameTechDev/UE4RealSensePlugin#8]
Hi,

I'm trying to install the realsense plugin for ue4.15 but it doesn't build.
realsense camera - R200
ue version - 4.15.3
realsense SDK 2016 R2 (unable to find 2016 R1)
visual studio community 2017.

Please let me know how to get it to build
Thanks

**Comment by kvoeten** [comment]
I'm getting a lot of errors too using UE 4.15.3, SDK 2016 R3 and VS 2015.
https://hastebin.com/kirirefuwo.tex

I'd rather not downgrade the engine version.. Is there any hope of the issue just being me? Or is the plugin going to get updated?

**Comment by kimba23** [comment]
Is this being maintained at all?

**Comment by kvoeten** [comment]
Doesn't look like it at all.
I found a fork someone made with SDK2 support, which already prompted way fewer errors, but still doesn't make this work considering intel's only supplying SDK3 at this moment on their site as far as I can tell.
